# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    hob.api.hob_app_service.endpoint: ~
    hob.api.hob_auth_service.endpoint: ~
    hob.api.hob_warehouse_service.endpoint: ~

services:

#### SERVICES #####
    hob.client.guzzle:
        class: HOB\ApiBundle\Client\GuzzleClient
        arguments: []

    hob.api.hob_auth_service:
        class: HOB\ApiBundle\Api\HOBAuthServiceApi
        arguments: ['@hob.client.guzzle', '%hob.api.hob_auth_service.endpoint%']

    hob.api.hob_app_service:
        class: HOB\ApiBundle\Api\HOBAppServiceApi
        arguments: ['@hob.client.guzzle', '%hob.api.hob_app_service.endpoint%']

    hob.api.hob_warehouse_service:
        class: HOB\ApiBundle\Api\HOBWarehouseServiceApi
        arguments: ['@hob.client.guzzle', '%hob.api.hob_warehouse_service.endpoint%']

